from __future__ import annotations
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime


class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    CRITICAL = "critical"
    ISOLATED = "isolated"
    RECOVERING = "recovering"


class ScenarioType(str, Enum):
    SCENARIO_DB_POOL_EXHAUSTED = "SCENARIO_DB_POOL_EXHAUSTED"
    SCENARIO_POD_OOM_KILLED = "SCENARIO_POD_OOM_KILLED"
    SCENARIO_DDOS_INGRESS = "SCENARIO_DDOS_INGRESS"


class IncidentSeverity(str, Enum):
    SEV1 = "SEV-1"
    SEV2 = "SEV-2"
    SEV3 = "SEV-3"
    NORMAL = "NORMAL"


class IncidentStatus(str, Enum):
    ACTIVE = "active"
    TRIAGING = "triaging"
    MITIGATING = "mitigating"
    RESOLVED = "resolved"
    IDLE = "idle"


class DAGStepStatus(str, Enum):
    PENDING = "pending"
    AWAITING_CONFIRMATION = "awaiting_confirmation"
    IN_PROGRESS = "in_progress"
    VERIFIED = "verified"
    FAILED = "failed"
    SKIPPED = "skipped"


class CloudProvider(str, Enum):
    AWS = "AWS"
    GCP = "GCP"
    AZURE = "Azure"


class PodInfo(BaseModel):
    id: str
    name: str
    phase: str = "Running"
    restart_count: int = 0
    ready: bool = True
    node_id: str
    cpu_usage_pct: float = 24.5
    memory_usage_mb: float = 512.0
    memory_limit_mb: float = 1024.0


class ServiceNode(BaseModel):
    id: str
    name: str
    role: str
    zone: str = "us-east-1a"
    host_node: str = "Node-01"
    status: HealthStatus = HealthStatus.HEALTHY
    latency_ms: float = 18.5
    error_rate_pct: float = 0.0
    rps: float = 450.0
    cpu_pct: float = 32.0
    memory_pct: float = 45.0
    active_connections: int = 15
    max_connections: int = 100
    replica_count: int = 3
    target_replicas: int = 3
    is_isolated: bool = False
    failover_target: Optional[str] = None
    upstream_ids: List[str] = Field(default_factory=list)
    downstream_ids: List[str] = Field(default_factory=list)
    pods: List[PodInfo] = Field(default_factory=list)


# Level-2 Predictive & Blast Radius Models
class PredictiveAnomalyScore(BaseModel):
    risk_level: str = "NOMINAL"
    failure_horizon_seconds: Optional[int] = None
    failure_horizon_text: str = "Nominal (> 30m)"
    metric_tracked: str = "PostgreSQL Primary Connection Gradient"
    current_value: float = 48.0
    projected_5m_value: float = 52.0
    growth_gradient_per_sec: float = 0.02
    preemptive_action_recommended: str = "Maintain baseline connection pool capacity"
    trajectory_points: List[float] = Field(default_factory=lambda: [45.0, 46.2, 47.0, 48.0, 49.5, 51.0, 52.0])


class BlastRadiusAssessment(BaseModel):
    risk_score_pct: float = 0.0
    canary_sandbox_status: str = "PASSED (0% Blast Radius)"
    isolated_zones: List[str] = Field(default_factory=list)
    affected_dependencies: List[str] = Field(default_factory=list)
    rollback_ready: bool = True
    safe_to_execute: bool = True


class BlackboxFrame(BaseModel):
    second_offset: int
    timestamp: str
    overall_health: str
    avg_latency_ms: float
    total_rps: float
    global_error_rate_pct: float
    active_connections_total: int
    critical_node: Optional[str] = None


class GitHotfixPR(BaseModel):
    pr_number: int = 1042
    title: str = "fix(db): add composite index on orders_v2 & increase pool timeout"
    branch: str = "hotfix/incident-zero-mitigation-db-lock"
    author: str = "IncidentZero AWS Bedrock Claude 3.5 Sonnet"
    status: str = "OPEN"
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    summary: str = "Automated zero-downtime mitigation hotfix generated by AWS Bedrock SRE agent."
    affected_files: List[str] = Field(default_factory=lambda: [
        "db/migrations/004_add_composite_index_orders.sql",
        "backend/config/database.py"
    ])
    unified_diff: str = ""
    commit_sha: str = "a9f81d4"


# Level-3 Multi-Agent Swarm & FinOps Models
class AgentVote(BaseModel):
    agent_id: str
    agent_name: str
    role: str
    vote: str
    confidence_pct: float = 99.4
    reasoning: str
    proposed_action: str
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class SwarmConsensusState(BaseModel):
    consensus_id: str = "SWARM-CON-01"
    incident_id: str
    consensus_action: str = "ISOLATE_NODE_03_AND_TRAFFIC_SHIFT"
    overall_confidence_pct: float = 99.4
    unanimous: bool = True
    participating_agents: int = 3
    votes: List[AgentVote] = Field(default_factory=list)
    debate_transcript: List[str] = Field(default_factory=list)
    converged_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class FinOpsMetrics(BaseModel):
    status: str = "HEALTHY"
    loss_per_min_usd: float = 0.0
    dropped_rps: float = 0.0
    sla_penalty_tier: str = "$0 Tier (Nominal)"
    capital_preserved_usd: float = 12650.0
    mttr_seconds: float = 3.4
    roi_efficiency_pct: float = 99.8
    total_exposure_accumulated_usd: float = 0.0


class AudioDebrief(BaseModel):
    incident_id: str
    executive_title: str = "IncidentZero Executive Incident Briefing"
    executive_script: str
    estimated_duration_sec: int = 20
    synthesized_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    audio_format: str = "speech_synthesis_web"


# Level-4 Immune & Voiceprint Models
class CloudAntibody(BaseModel):
    id: str
    policy_name: str
    rule_type: str
    description: str
    target_scenario: ScenarioType
    active: bool = True
    blocked_recurring_count: int = 0
    synthesized_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    opa_rego_policy: str = ""


class VoiceSignatureAuth(BaseModel):
    verified: bool = True
    operator: str = "Lead Principal SRE (Authorized)"
    confidence_pct: float = 99.8
    signature_hash: str = "ed25519_sig_9f82ca71d34b9e02"
    spectrogram_entropy: float = 0.942
    verified_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class RegionNodeStatus(BaseModel):
    region_id: str
    region_name: str
    status: str
    latency_ms: float
    healthy: bool = True
    active_connections: int = 240
    packet_loss_pct: float = 0.0


class GlobalMeshState(BaseModel):
    active_primary_region: str = "us-east-1"
    mesh_protocol: str = "Envoy eBPF / BGP Anycast"
    regions: List[RegionNodeStatus] = Field(default_factory=list)
    last_failover_at: Optional[str] = None
    zero_packet_drop_verified: bool = True


# ================================================================
# LEVEL-5 SOVEREIGN SINGULARITY MODELS
# ================================================================

class MultiCloudProviderStatus(BaseModel):
    provider: CloudProvider
    region: str
    status: str  # ACTIVE, WARM_STANDBY, COLD_STANDBY
    latency_ms: float
    cost_per_m_req_usd: float
    ai_engine: str  # AWS Bedrock Claude 3.5, GCP Vertex AI Gemini 1.5, Azure OpenAI GPT-4o


class SovereignMeshState(BaseModel):
    active_provider: CloudProvider = CloudProvider.AWS
    evacuation_status: str = "STABLE_SOVEREIGN"
    providers: List[MultiCloudProviderStatus] = Field(default_factory=lambda: [
        MultiCloudProviderStatus(provider=CloudProvider.AWS, region="us-east-1", status="ACTIVE", latency_ms=12.4, cost_per_m_req_usd=0.18, ai_engine="AWS Bedrock Claude 3.5 Sonnet"),
        MultiCloudProviderStatus(provider=CloudProvider.GCP, region="us-central1", status="WARM_STANDBY", latency_ms=18.1, cost_per_m_req_usd=0.16, ai_engine="GCP Vertex AI Gemini 1.5 Pro"),
        MultiCloudProviderStatus(provider=CloudProvider.AZURE, region="eastus", status="COLD_STANDBY", latency_ms=24.2, cost_per_m_req_usd=0.22, ai_engine="Azure OpenAI GPT-4o"),
    ])
    last_evacuation_log: Optional[str] = None
    zero_downtime_preserved: bool = True


class AdversarialBattleRound(BaseModel):
    round_id: int
    attacker_name: str = "Autonomous Red-Team GAN (Zero-Day Invariant Probe)"
    defender_name: str = "Self-Evolving Blue-Team Immune Sentinel"
    attack_vector: str = "Zero-Day Memory Leak Infiltration on /v2/auth/oauth"
    defense_action: str = "eBPF Kernel Trap & Micro-Enclave Auto-Quarantine"
    intercept_time_ms: float = 3.8
    result: str = "DEFENDED (0s Impact)"
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class RedTeamGANState(BaseModel):
    is_dueling: bool = False
    total_battles_fought: int = 142
    total_attacks_neutralized: int = 142
    neutralization_rate_pct: float = 100.0
    avg_intercept_time_ms: float = 4.2
    recent_rounds: List[AdversarialBattleRound] = Field(default_factory=list)


# ================================================================
# TOPOLOGY & STATE MODELS
# ================================================================

class TopologyState(BaseModel):
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    environment: str = "production-aws-east"
    overall_health: HealthStatus = HealthStatus.HEALTHY
    nodes: Dict[str, ServiceNode] = Field(default_factory=dict)
    active_connections_total: int = 45
    total_rps: float = 2480.0
    avg_latency_ms: float = 18.2
    global_error_rate_pct: float = 0.0
    predictive_radar: Optional[PredictiveAnomalyScore] = None
    blast_radius: Optional[BlastRadiusAssessment] = None
    swarm_consensus: Optional[SwarmConsensusState] = None
    finops: Optional[FinOpsMetrics] = None
    active_antibodies: List[CloudAntibody] = Field(default_factory=list)
    global_mesh: Optional[GlobalMeshState] = None
    sovereign_mesh: Optional[SovereignMeshState] = None
    red_team_gan: Optional[RedTeamGANState] = None


class TelemetryLog(BaseModel):
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    level: str = "INFO"
    source: str = "system"
    message: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class DAGStep(BaseModel):
    id: str
    step_number: int
    title: str
    description: str
    tool_name: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    destructive: bool = False
    requires_voice_confirmation: bool = False
    status: DAGStepStatus = DAGStepStatus.PENDING
    output: Optional[str] = None
    duration_ms: Optional[float] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None


class RemediationDAG(BaseModel):
    dag_id: str
    incident_id: str
    title: str
    rationale: str
    severity: IncidentSeverity = IncidentSeverity.SEV1
    status: DAGStepStatus = DAGStepStatus.PENDING
    steps: List[DAGStep] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    completed_at: Optional[str] = None
    requires_confirmation: bool = True
    confirmed_by_voice: bool = False
    hotfix_pr: Optional[GitHotfixPR] = None
    swarm_consensus: Optional[SwarmConsensusState] = None
    voice_auth: Optional[VoiceSignatureAuth] = None
    formal_verification_proof: str = "PROVED (0 Hallucination Risk / Complete SMT Verification)"


class IncidentRecord(BaseModel):
    incident_id: str
    scenario_id: Optional[ScenarioType] = None
    title: str
    severity: IncidentSeverity = IncidentSeverity.NORMAL
    status: IncidentStatus = IncidentStatus.IDLE
    root_cause: Optional[str] = None
    affected_nodes: List[str] = Field(default_factory=list)
    detected_at: Optional[str] = None
    resolved_at: Optional[str] = None
    active_dag: Optional[RemediationDAG] = None
    hotfix_pr: Optional[GitHotfixPR] = None
    swarm_consensus: Optional[SwarmConsensusState] = None
    finops: Optional[FinOpsMetrics] = None
    audio_debrief: Optional[AudioDebrief] = None


class PostmortemReport(BaseModel):
    incident_id: str
    scenario_name: str
    severity: IncidentSeverity
    detected_at: str
    resolved_at: str
    time_to_detect_ms: int = 420
    time_to_mitigate_ms: int = 1850
    executive_summary: str
    root_cause_analysis: str
    remediation_actions: List[str]
    preventative_measures: List[str]
    sla_compliance_pct: float = 99.99
    mcp_tools_invoked: List[str] = Field(default_factory=list)
    git_hotfix_pr_url: Optional[str] = None


class MCPToolCallResponse(BaseModel):
    tool_name: str
    success: bool
    result: Dict[str, Any] = Field(default_factory=dict)
    message: str = ""
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class TriggerScenarioRequest(BaseModel):
    scenario_id: ScenarioType


class ConfirmDAGRequest(BaseModel):
    dag_id: str
    confirmation_method: str = "voice"


class MCPToolCallRequest(BaseModel):
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)


class VoiceCommandRequest(BaseModel):
    transcript: str
    speaker_id: Optional[str] = "sre-operator-1"
    confidence: float = 0.95


class VoiceCommandResponse(BaseModel):
    recognized_intent: str
    action_taken: str
    spoken_feedback: str
    requires_confirmation: bool = False
    dag: Optional[RemediationDAG] = None
    hotfix_pr: Optional[GitHotfixPR] = None
    swarm_consensus: Optional[SwarmConsensusState] = None
    audio_debrief: Optional[AudioDebrief] = None
    voice_auth: Optional[VoiceSignatureAuth] = None
